### Root
GET http://localhost:5000

### Users
GET http://localhost:5000/api/users

### Test body of request
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "Gagandeep Singh",
    "email": "singh.gagandeep3911@gmail.com",
    "password": "123456"
}

### Auth
GET http://localhost:5000/api/auth

#### Posts
GET http://localhost:5000/api/posts

#### Profile
GET http://localhost:5000/api/profile

#### Generate a token
POST http://localhost:5000/api/auth
Content-Type: application/json

{
    "email": "singh.gagandeep3911@gmail.com",
    "password": "123456"
}

#### Fetch Current profile
GET http://localhost:5000/api/profile/me
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

{
    "email": "singh.gagandeep3911@gmail.com",
    "password": "123456"
}

#### Create a new Profile
POST http://localhost:5000/api/profile/
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

{
    "status": "Developer",
    "skills": "HTML, CSS"
}

#### Fetch Profile By ID
GET http://localhost:5000/api/profile/user/5f490187b29e134d14536158

#### Delete a user
DELETE http://localhost:5000/api/profile
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY0OTA5YjA0ZTJlOTQyNjg4MTkwYWYwIn0sImlhdCI6MTU5ODYyMjEyOCwiZXhwIjoxNTk4OTgyMTI4fQ.t5XxO1sQe5OF-QZNr5ZEQTsnVM5F4QJCqrvDclFJnh4

#### 
PUT http://localhost:5000/api/profile/experience
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

{
    "title": "Senior Developer",
    "company": "Imagination",
    "location": "Hell",
    "from": "12-12-2020",
    "current": true,
    "description": "Web Developer"
}

#### Delete experience 

DELETE http://localhost:5000/api/profile/experience/5f490187b29e134d14536158
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

#### Add education
PUT http://localhost:5000/api/profile/education
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

{
    "school": "Home School",
    "degree": "Violinist",
    "fieldofstudy": "Music",
    "from": "12-12-2020",
    "current": true,
    "description": "Student"
}

#### Delete education
DELETE http://localhost:5000/api/profile/education/5f496399a791e02ee4ba3b9b
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

#### Fetch github repository
GET http://localhost:5000/api/profile/github/gagandeep39

#### Create post
POST http://localhost:5000/api/posts
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

{
    "text": "I want to kill myself"
}

#### Fetch All posts
GET http://localhost:5000/api/posts
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

#### Fetch Post by ID
GET http://localhost:5000/api/posts/5f4a14fdda8cca4b5c02704b
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

#### Delete Post by ID
DELETE http://localhost:5000/api/posts/5f4a14fdda8cca4b5c02704b
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

#### Like a post
PUT http://localhost:5000/api/posts/like/5f4a20a55e19662968dbf250
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

#### Like a post
PUT http://localhost:5000/api/posts/unlike/5f4a20a55e19662968dbf250
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

#### Create a comment
POST http://localhost:5000/api/posts/comment/5f4a20a55e19662968dbf250
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ

{
    "text": "You are gonna be fine"
}

#### Delete a comment
DELETE http://localhost:5000/api/posts/comment/5f4a20a55e19662968dbf250/5f4a4be5cfbf6d49d4b3c80f
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWYyYWE3OWRkNmI2MmUyMDkwNTAzMDdhIn0sImlhdCI6MTU5ODYxNzkxNiwiZXhwIjoxNTk4OTc3OTE2fQ.kK20Z4hf2LOivbhjDnc12OlfqXjHb_vuwnf9FvPDHXQ
