### Root
GET http://localhost:5000

### Users
GET http://localhost:5000/api/users

### Test body of request
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Test Validation",
    "email": "test3@validations.com",
    "password": "123456",
    "password2": "123456"
}

### Auth
GET http://localhost:5000/api/users
Authorization: [Generate Token by logging In]


#### Posts
GET http://localhost:5000/api/posts

#### Profile
GET http://localhost:5000/api/profile

#### Generate a token
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "singh.gagandeep3911@gmail.com",
    "password": "123456"
}

#### Fetch Current profile
GET http://localhost:5000/api/profile/me
Authorization: [Generate Token by logging In]

#### Create a new Profile
POST http://localhost:5000/api/profile/
Content-Type: application/json
Authorization: [Generate Token by logging In]

{
    "status": "Developer",
    "skills": "HTML, CSS"
}

#### Fetch Profile By ID
GET http://localhost:5000/api/profile/user/5f2aa79dd6b62e209050307a

#### Delete a user
DELETE http://localhost:5000/api/profile
Authorization: [Generate Token by logging In]

#### 
PUT http://localhost:5000/api/profile/experience
Content-Type: application/json
Authorization: [Generate Token by logging In]

{
    "title": "Senior Developer",
    "company": "Imagination",
    "location": "Hell",
    "from": "12-12-2020",
    "current": true,
    "description": "Web Developer"
}

#### Delete experience 

DELETE http://localhost:5000/api/profile/experience/5f4f3719706f091e08da645a
Content-Type: application/json
Authorization: [Generate Token by logging In]

#### Add education
PUT http://localhost:5000/api/profile/education
Content-Type: application/json
Authorization: [Generate Token by logging In]

{
    "school": "Home School",
    "degree": "Violinist",
    "fieldofstudy": "Music",
    "from": "12-12-2020",
    "current": true,
    "description": "Student"
}

#### Delete education
DELETE http://localhost:5000/api/profile/education/5f496399a791e02ee4ba3b9b
Content-Type: application/json
Authorization: [Generate Token by logging In]

#### Fetch github repository
GET http://localhost:5000/api/profile/github/gagandeep39

#### Create post
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: [Generate Token by logging In]

{
    "text": "Demo Post"
}

#### Fetch All posts
GET http://localhost:5000/api/posts
Content-Type: application/json
Authorization: [Generate Token by logging In]

#### Fetch Post by ID
GET http://localhost:5000/api/posts/5f4a14fdda8cca4b5c02704b
Content-Type: application/json
Authorization: [Generate Token by logging In]

#### Delete Post by ID
DELETE http://localhost:5000/api/posts/5f4a14fdda8cca4b5c02704b
Content-Type: application/json
Authorization: [Generate Token by logging In]

#### Like a post
PUT http://localhost:5000/api/posts/like/5f4a20a55e19662968dbf250
Content-Type: application/json
Authorization: [Generate Token by logging In]

#### Like a post
PUT http://localhost:5000/api/posts/unlike/5f4a20a55e19662968dbf250
Content-Type: application/json
Authorization: [Generate Token by logging In]

#### Create a comment
POST http://localhost:5000/api/posts/comment/5f4a20a55e19662968dbf250
Content-Type: application/json
Authorization: [Generate Token by logging In]

{
    "text": "You are gonna be fine"
}

#### Delete a comment
DELETE http://localhost:5000/api/posts/comment/5f4a20a55e19662968dbf250/5f5499c31699680914ae7d36
Content-Type: application/json
Authorization: [Generate Token by logging In]
